### ISSUE TITLE
Cannot install Distance (Bugzilla #91)

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/distance-bugs#112]
status NEW severity *normal* in component *01) Installation* for *---*
Reported in version *6.0 Release 2* on platform *PC*
Assigned to: Laura Marshall

On 2011-03-11 03:05:09 +0000,  wrote:

> I am unable to install Distance 6.0 R2 using Windows 7 Ultimate (with Serv. pack 1; 32-bit operating system) on a Sony Vaio laptop.
> I receive the error message: "MSVCP60.dll could not be opened.  Please check that your disk is not full & that you have access to the destination directory"
> I have 100 GB of space on the drive, and the permissions on the system32 folders says I have "read & execute" permission.  I have tried installing as an administrator, checking for viruses/malware, running Sfc /scannow
> at the command prompt. All other of my usual programs (including Presence,MARK)  so far I can install. Any suggestions would be greatly appreciated.

On 2011-03-28 18:47:25 +0100, Laura Marshall wrote:

> (In reply to comment # 0)
> > I am unable to install Distance 6.0 R2 using Windows 7 Ultimate (with Serv.
> > pack 1; 32-bit operating system) on a Sony Vaio laptop.
> > I receive the error message: "MSVCP60.dll could not be opened.  Please check
> > that your disk is not full & that you have access to the destination directory"
> > I have 100 GB of space on the drive, and the permissions on the system32
> > folders says I have "read & execute" permission.  I have tried installing as an
> > administrator, checking for viruses/malware, running Sfc /scannow
> > at the command prompt. All other of my usual programs (including Presence,MARK)
> >  so far I can install. Any suggestions would be greatly appreciated.
> 
> 
> The following steps may resolve this issue:
> 
> 1) Rename the MSVCP60.dll file in the System32 folder to something like MSVCP60_orig.dll (Note, to do this you may need to take ownership of the file as it may be owned by Trusted Installer. See instructions at http://helpdeskgeek.com/windows-7/windows-7-how-to-delete-files-protected-by-trustedinstaller/ )
> 2) Install Distance
> 3) Delete the MSVCP60.dll file Distance installed from the System32 folder.
> 4) Rename MSVCP60_orig.dll back to MSVCP60.dll
> 5) For security reset the permission on the MSVCP60.dll file to what they were originally.

**Comment by Mgamerz** [comment]
I am having this exact issue on some machines at my workplace. Your steps to resolve this issue didn't seem to work for me, it still says it cannot read that file (even though it doesn't exist anymore).

Running Windows 8.1 x64 Pro, plenty of resources to spare. Why is this program attempting to modify windows files?

**Comment by LHMarshall** [comment]
This is a duplicated bug already logged in #19
