### ISSUE TITLE
Online Help for the R libraries does not work

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/distance-bugs#134]
Version: Distance 7 Alpha

In the Help menu in Distance there is an option for Online Manuals which gives links to help in the distance packages as well as the Distance user manual. These options referring to the R libraries link to the index html file for each of these R libraries but the links on these pages do not work as later versions of R no longer generate static html pages by default.

**Comment by dill** [comment]
One way around this is to spawn an R process in the background to serve 
the pages (basically as R does, see ?startDynamicHelp). BUT the problem 
there is when to stop that process (obviously when Distance is closed 
but maybe before?)

Another option is to simply link to the PDFs, though they are less nice 
to copy/paste from.

**Comment by LHMarshall** [comment]
Dave,
I don't get notification of new bugs, can I get that switched on again please.
Also can you let me know when you link the Distance 7 download stuff to the website so I can send out a notification to the mailing list please,
Thanks,
Laura


Dr. L. Marshall
Centre for Research into Ecological and Environmental Modelling
University of St. Andrews 

     On Tuesday, 3 March 2015, 15:52, DL Miller <notifications@github.com> wrote:
   
 

 One way around this is to spawn an R process in the background to serve 
the pages (basically as R does, see ?startDynamicHelp). BUT the problem 
there is when to stop that process (obviously when Distance is closed 
but maybe before?)

Another option is to simply link to the PDFs, though they are less nice 
to copy/paste from.

**Comment by LHMarshall** [comment]
These have now been removed from the Distance interface. Users should consult the library pdf which can be found online on the CAN site or the help within R.
