### ISSUE TITLE
Running mrds with fresh install of Distance 7 and R 3.2.1

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/distance-bugs#143]
After installing both pieces of software, proceed to run Golftees project
* Fail
    - Set environment variable `R_LIBS` = `C:\Users\xx\Documents\R\win-library`  (as described http://distancesampling.org/Distance/old-versions/d62-r-install-details.html)
* Package installation works OK (via `install.distance.packages` in `support.r`)
    - `library(mrds)` fails
        - No package `optextras setRNG dfoptim svUnit`
    - after installing these packages into `3.2.1` of `win-library`, golftees and dolphins (dsm) run to completion
* did not test DSsim or mads code

**Comment by LHMarshall** [comment]
I have added the mrds dependencies to the Distance 7 Beta 1 release ( `optextras setRNG dfoptim svUnit`)
