### ISSUE TITLE
Distance 7.1. Bug

### ISSUE THREAD

**Issue by Tullimonstrum** [DistanceDevelopment/distance-bugs#179]
Fitting a detection function. All goes well but I get a red tab at the end with the message 
R Error: Error in remove.mrds.support.functions(): could not find "remove.mrds.support.functions" Execution halted. 

Charles is writing this so you can see me in my office for further details

**Comment by erex** [comment]
Can't duplicate the error using D7.1r1 on the crabeater seal exercise data.  Portion of the log window that "should" cause a problem, but does not return an error

```
> sink()
> 
> write.stats.dht('C:\\Users\\eric\\AppData\\Local\\Temp\\dst49760\\stat.r',T,dht.3)
> 
> remove.mrds.support.functions()
> remove.support.functions()
> 
> 
> proc.time()
```

**Comment by erex** [comment]
Hmm, working in the computer lab with D7.1R1 (freshly downloaded from website today 27Jul17) and I **can** reproduce the error reported by Charles.

![image](https://user-images.githubusercontent.com/330744/28661726-820f171a-72af-11e7-9e82-63e3a2588fa6.png)

It would appear that remov.mrds.support.functions() is called *twice*.  On its first call, it deletes itself, hence throws the error when called the second time.

Mystery is why the D7.1R1 just downloaded has the duplicated call, whereas version on my computer does not.

**Comment by erex** [comment]
### More details:
The error is reproducible on my machine.  Error arises when user requests workspace tidying in Preferences | R Options:

![image](https://user-images.githubusercontent.com/330744/28667201-6e16137c-72c2-11e7-9c4f-a0082fdf7cdd.png)

Unticking that box produces no errors.  Checking now with Charles...

**Comment by LHMarshall** [comment]
Issue is the same for mads, dsm and DSsim, I have now changed the NEngineInterfaces so that remove.xxx.support.functions() is only called when the user selects 'Remove the new R objects that are created with each run" will push these changes tomorrow. Although I'm a little unsure if the functionality is as intended by @lenthomas ?

**Comment by lenthomas** [comment]
No, this is not what I intended.  It's supposed to remove some temporary functions each time there's a run.

**Comment by LHMarshall** [comment]
Ok will modify further

**Comment by LHMarshall** [comment]
No idea why I messed this up... I'm sure what was there had caused some issue... need to keep an eye on this to make sure it works now.
