### ISSUE TITLE
Object variable or With block variable not set

### ISSUE THREAD

**Issue by ChristopheCleguer** [DistanceDevelopment/distance-bugs#181]
Hi, 
I am trying to develop a systematic random parallel line sampling design. Below is the error message I get when running the design engine. Does anyone know what the issue is and how to solve it please? 

** Error: Unexpected error in Design Engine.
Error number: -2147211505
Error source: D7DesEng.CoverageProbabilityGrid.CalculateProbabilities
Error description: Unexpected error in Distance Design Engine.
Source: D7DesEng.CoverageProbabilityGrid.CalculateProbabilities
Internal Error number: 91.
Internal Error description: "Object variable or With block variable not set".
 Log: 
About to read design definition. 

About to read design definition. 
Initializing general design properties. 
Selecting the design class. 
Selecting the design sampler. 
Initializing the line sampler properties. 
Initializing the coverage probability grid properties. 
Calculating the overall coverage probabilities. 
Starting simulations for stratum number 1. 
  **

**Comment by LHMarshall** [comment]
I will need to see a copy of the project to figure out what is going wrong here. Could you please attach here or E-mail it to the distance E-mail address then add a note here so I can look out for it. Thanks

**Comment by ChristopheCleguer** [comment]
Hi Laura,

I think this has been sorted.
Thank you
Regards
Chris

**Comment by LHMarshall** [comment]
Ah yes I see @erex Eric dealt with this via google groups... Eric can this be closed?

**Comment by erex** [comment]
yep
