### ISSUE TITLE
survey design ok data analysis not ok

### ISSUE THREAD

**Issue by SteveBlakeWCS** [DistanceDevelopment/distance-bugs#188]
Hi,

working on most basic dataset for course development, my new distance 7.3 does not complete the first analysis in the exercise (the half normal no adjustments), or any other analyses I try to perform with any other data. the message I get is the following:

Initializing 
Making Data File 
Making Data Selection Queries 
Making Input File 
Engine started with the following command:
 C:\PROGRA~2\Distance 7\ec "C:\PROGRA~2\Distance 7\MCDS.exe 0, C:\Users\steve\AppData\Local\Temp\dstF6C3.tmp \options 2>C:\Users\steve\AppData\Local\Temp\dstF6C2.tmp" 
-- Start of Analyis Engine Log File -- 
-- End of Analyis Engine Log File -- 
** Warning: Analysis engine wrote some output to the console error stream, reproduced below. **
-- Start of Console Error Stream -- 
'C:\PROGRA~2\Distance' is not recognized as an internal or external command,
operable program or batch file.
 
-- End of Console Error Stream -- 
Analysis engine status 'OK' 
Reading Results 
Run finished 

![distance error](https://user-images.githubusercontent.com/54447899/63605874-71684000-c594-11e9-9d0f-29fbcd200e82.JPG)

I tried uninstalling reinstalling etc, to no avail. any ideas?
thanks so much
Steve Blake

**Comment by erex** [comment]
Steve

Pay a visit to the Distance Google groups email list, where this question comes up from time to time.  For some machines, the space in the path throws the error you see.

Details in this message on the Google list:
https://groups.google.com/forum/#!searchin/distance-sampling/C$3A%5Cprogra~%5Cdistance$207%5Cec%7Csort:date/distance-sampling/pdBJdCg7oR4/OqPEScWOEAAJ

Easy solution, install Distance 7.3 into a directory that does not have a space in the path name, like "C:/Distance"

**Comment by SteveBlakeWCS** [comment]
thanks so much for your help. I ddn't see this til now,
