### ISSUE TITLE
Discrepancy in number of observations by both observers in mrds

### ISSUE THREAD

**Issue by annepstpierre** [DistanceDevelopment/distance-bugs#191]
Hi! - not sure if a bug or a problem with my code/dataset.
I have a dataset containing observations of porpoises in which I have identified duplicates (i.e. seen by both observers - it was a double-platform plane survey). I have organized my data correctly to import for mrds analyses in R (it also loads correctly in Distance Software). I am running the following code : 

`finalmodel<- ddf(method= "io", dsmodel= ~mcds(key=hn, formula=~1), mrmodel= ~glm(~distance+Beaufort), data= datasetPpFull, meta.data=list(width=571,left=118))`

By investigating the data observations between the left and right truncation distances, I know that my dataset contains 185 unique observations, that 105 observations have been made by the primary observer, that 94 observations were made by the secondary observer, and that there are 14 duplicate observations. 

However, then running the summary for my mrds model (i.e., `summary(finalmodel)` ), it spits out the following:

Summary for io.fi object
Number of observations: 185
Number seen by primary: 105
Number seen by secondary : 94
Number seen by both: 21      

I don't understand why this summary is telling me there's 21 observations seen by both observers, when there are only 14 in the dataset. I don't have this problem when running the same analysis with data of different species from the same survey. How are the numbers in the summary calculated? How to troubleshoot what could be causing this difference?

Please let me know if this is more suitable for the email list than here.

**Comment by dill** [comment]
These numbers are generated from looking at the `observer` and `detected` columns in your data. For example, number seen by primary is calculated as:

```r
length(newdat$distance[newdat$observer==1&newdat$detected==1])
```

if `newdat` is your data. For secondary detections you calculate the same thing but with `newdat$observer==1` and for both it calculates first the number of times the object was detected:

```r
 timesdetected <- newdat$detected[newdat$observer==1] +
                  newdat$detected[newdat$observer==2]
```

then looks for when this is 2. If you can investigate the `observer` column of your data, you might find that there is some discrepency between this column and what you think it should be. If you don't then please post a small, reproducible example and I can take a look to see if there's a bug (feel free to e-mail me if you'd rather not post data etc online, I will only use your data for bug fixing, then delete it).

Hope this helps!

**Comment by dill** [comment]
I think this was resolved over e-mail, but do reply back if that's not the case.

Closing this issue.
