### ISSUE TITLE
first analysis

### ISSUE THREAD

**Issue by 27ivasal27** [DistanceDevelopment/distance-bugs#194]
Hello, I have used old versions of distance, now I have retaken the analysis with the new distance 7.3 version, but in the firts installation and running the example i have an error in the data analysis. I installed the program in the default folder and didn´t work and installing in another folder and have problems too. Please help me to fix that

Initializing 
Making Data File 
Making Data Selection Queries 
Making Input File 
Engine started with the following command:
 C:\Distance 7\ec "C:\Distance 7\MCDS.exe 0, C:\Users\iss\AppData\Local\Temp\dstB676.tmp \options 2>C:\Users\iss\AppData\Local\Temp\dstB675.tmp" 
-- Start of Analyis Engine Log File -- 
-- End of Analyis Engine Log File -- 
** Warning: Analysis engine wrote some output to the console error stream, reproduced below. **
-- Start of Console Error Stream -- 
"C:\Distance" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
 
-- End of Console Error Stream -- 
Analysis engine status 'OK' 
Reading Results 
Run finished

**Comment by erex** [comment]
Pleased to know you have installed a the latest version of Distance.  The problem you report comes up quite often in the Distance email list.

The solution to this problem has been described on that email list:

>To install Distance software in different location than the default location; specifically install into a directory that does not contain spaces: as "Distance7" rather than default name with space before 7 as in "Distance 7".

Reinstall, then let us know whether that solution was successful.

**Comment by 27ivasal27** [comment]
i have a lot of problems to unistall distance but i got it and then i follow your instructions and now its working good... thanks for your help

**Comment by erex** [comment]
Pleased to hear the software is now working for you.
