### ISSUE TITLE
Analysis engine terminated unexpectedly

### ISSUE THREAD

**Issue by JReid03** [DistanceDevelopment/distance-bugs#199]
Trying to run a simple analysis for some line transect data and I'm getting the following error message:
###
Initializing 
Making Data File 
Making Data Selection Queries 
Making Input File 
Engine started with the following command:
 C:\PROGRA~2\DISTAN~1\ec "C:\PROGRA~2\DISTAN~1\MCDS.exe 0, C:\Users\JONATH~1\AppData\Local\Temp\dst50E7.tmp \options 2>C:\Users\JONATH~1\AppData\Local\Temp\dst50E6.tmp" 
** Error: Analysis engine terminated unexpectedly (with error code -1073741760).  **
-- Start of Analyis Engine Log File -- 
 This is mcds.exe version 6.2.0     
 Options;                                                                      
 Type=Line;                                                                    
 Length /Measure='Kilometer';                                                  
 Distance=Perp /Measure='Kilometer';                                           
 Area /Units='Square kilometer';                                               
 Object=Single;                                                                
 SF=1;                                                                         
 Selection=Specify;                                                            
 Confidence=95;                                                                
 Print=Selection;                                                              
 End;                                                                          
 Data /Structure=Flat;                                                         
 Fields=STR_LABEL, STR_AREA, SMP_LABEL, SMP_EFFORT, DISTANCE;                  
 Infile=C:\Users\JONATH~1\AppData\Local\Temp\dst50D5.tmp /NoEcho;              
 Data will be input from file - [...]APPDATA\LOCAL\TEMP\DST50D5.TMP
 
-- End of Analyis Engine Log File -- 
** Warning: Analysis engine wrote some output to the console error stream, reproduced below. **
-- Start of Console Error Stream -- 
forrtl: severe (64): input conversion error, unit -5, file Internal Formatted Read

Image              PC        Routine            Line        Source             
MCDS.exe           004AFF79  Unknown               Unknown  Unknown
 
-- End of Console Error Stream -- 
Analysis engine status 'Run failed - analysis engine encountered an unknown error, possibly in the input or output files' 
Reading Results 
Run finished 

#####
![Distance Analysis error](https://user-images.githubusercontent.com/79090674/107954617-958fbc00-6f94-11eb-8d6d-7fdf55271aba.png)

Does anyone have any suggestions please?

**Comment by erex** [comment]
Jonathan

This is an unusual message; don't know that I've seen it before.  
- I gather you're using the covariate analysis engine because you have covariates in your detection function?  
- Perhaps something is amiss within the data
    - have you searched the data fields themselves for some wild character?
- Have you run other models on this set of data (with the same set of filters), perhaps without the covariate?

Let me know the answers to the above; if you're still stumped, Zip up the project (File | Export) and upload to this issue so I can have a look.

**Comment by JReid03** [comment]
[1703Test.dat.zip](https://github.com/DistanceDevelopment/distance-bugs/files/5982368/1703Test.dat.zip)

Hi, 
Thanks for the prompt reply. I have been basing my analysis of the minke whale data set. Look through the data I can not see and errors/mistakes with data entry.

The data set is very similar to the Minke whale data set. Originally my text file included group size, but I removed this to try and troubleshoot the error message.

I've attached the project file and appreciate any input.

Thanks,
Jonathan

**Comment by erex** [comment]
Thanks Jonathan.  The .zip file you uploaded is incomplete.  Distance stores things in various places on your computer.  Use the File | Export facility
![image](https://user-images.githubusercontent.com/330744/107965299-45b7f180-6fa2-11eb-85c7-fb503f79c95e.png)

because the programme will collect up all the bits I need to run your analysis.  Export and upload again please.

**Comment by JReid03** [comment]
[1703Test.zip](https://github.com/DistanceDevelopment/distance-bugs/files/5982529/1703Test.zip)

Second time lucky.

Thanks

**Comment by erex** [comment]
Never trust that your data are accurate, without a visual inspection
![image](https://user-images.githubusercontent.com/330744/107969351-941bbf00-6fa7-11eb-8115-5bbdfea5b175.png)

- I changed those 2 values to "8" and
- I made all the transect labels unique.  You had several transects labelled 18 or something; that might have confused the software.

The code runs when those two changes are made.  But the estimates are astronomical, something like a million animals in the study area.  Are you sure you have your units recorded correctly?  Your transects are hundreds of kilometers in length, but your detections are seldom more than 10m from the transect.  Are perpendicular distances measured in meters or kilometers?

**Comment by JReid03** [comment]
Thank you. I don't know how I had missed these ones. 

And yes the units are incorrect, I quickly recreated the project file before sending it through to you and didn't change all of my units so hopefully the estimated number should drop. 

Thanks again for your help. 

Jonathan
