### ISSUE TITLE
Distance for Windows 7.3 R2 stores incorrect values from dsm predict, related to regional (locale-specific) representation of decimal values

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/distance-bugs#200]
Distance 7.3 R2; R 4.0.3; mrds 2.2.4

Issue reported by Rasmus Bisschop-Larsen to distance-sampling list on 22/2/2021.

"I have a specific question about the densities appended to the prediction grid (under the Data tab) in Distance after running the DSM prediction. I have a very hard time matching it to the density plot shown in the Analysis results. My densities in the grid seem to be a factor 10^9 higher and not consistently indicating where the decimal position is. This gives me problems when exporting the data to an external GIS platform as some values show as being a factor 10 lower than they are supposed to be. As it is not consistent I cannot correct it by a formula. I have dug around for a few days in the R code etc. and cannot figure out why the numbers is or where in the code they are appended. The rest of the analysis run as expected and all relevant units are in meters. Do anyone have a suggestion on how to solve the problem?"

At my suggestion, he tried changing his windows 10 settings to UK and this fixed the problem.  The problem can be reproduced in the sample project Dolphins by setting regional settings to Danish.

**Comment by lenthomas** [comment]
On inspection, this is caused by the `write.table()` function used in the R code written by the dsm engine -- for example (from dolphin project): 
```
grid.6$D.hat<- predict(dsm.5,newdata=grid.6, off.set=1)
write.table(grid.6$D.hat, file='C:\\Users\\len\\AppData\\Local\\Temp\\dst43677\\pred.res.r', quote=FALSE, col.names=FALSE, sep='\t')
```

The default in `write.table` is to use a dot for decimal, and this is not the Danish regional setting.  The file that is written out is then read in by the VB function in the DSM NEngineInterface D7DSMNEI CClsDatabaseInterface.SaveGridResFileContents.  This has the code

```
        strD = Mid(strLine, lngSep)
        If (IsNumeric(strD)) Then
            dblD(lngID - 1) = CDbl(strD)
        Else
            dblD(lngID - 1) = mdblMISSING_VALUE
        End If
```

I think the issue is in the `CDbl(strD)`.  The strD needs to be converted to a locale-specific numeric string first.  Luckily, there is a robust function in D7Util already for this (it's robust in that it does nothing to the string if the intput is not a locale independent string), so I think we just need to replace
```
        strD = Mid(strLine, lngSep)
```
with
```
        strD = LocaleDepDec(Mid(strLine, lngSep))
```

**Comment by lenthomas** [comment]
I just ran a quick test on the version of the Distance virtual machine I have and this appears to work; I don't have an up-to-date version of the VM however, so I'll leave as open @LHMarshall

**Comment by erex** [comment]
> The default in `write.table` is to use a dot for decimal, and this is not the Danish regional setting. The file that is written out is then read in by the VB function in the DSM NEngineInterface D7DSMNEI CClsDatabaseInterface.SaveGridResFileContents. This has the code
> 
> ```
>         strD = Mid(strLine, lngSep)
>         If (IsNumeric(strD)) Then
>             dblD(lngID - 1) = CDbl(strD)
>         Else
>             dblD(lngID - 1) = mdblMISSING_VALUE
>         End If
> ```
> 

If Git Blame were available to us at the time, I expect it would say the offending line of code was written by yours truly in late 2005.

**Comment by LHMarshall** [comment]
@lenthomas added it to the next Dec milestone and assigned to myself

**Comment by lenthomas** [comment]
Just noting (for the record) that this bug was also reported by Ainars Aunins on the distance list on 20/Aug/2021 so we should also contact him once it's resolved.

**Comment by LHMarshall** [comment]
@erex @lenthomas This is now fixed in the [XP dev VM](https://github.com/DistanceDevelopment/distance-for-windows/commit/55c85aae4d36f16e87e268daa21997968c21e6e8) I have a recompiled dll if anyone wants to test if just replacing the dll is a workable fix until the next version release.. otherwise I will try to test that at some point. Sadly I cannot just attach the dll here.

**Comment by erex** [comment]
Laura--want to understand your request.  Are you suggesting you could email  `D7DSMNEI.dll` swap with the current `dll` in the `Program Files (x86)/Distance 7` directory to try on my Windows machine.  Then change my locale settings to Denmark, to see if the prediction grid cells are populated properly?

If all the above works, then you could write to the list attaching the `dll` with instructions for the Danes?

If so, send along the `.dll`

**Comment by erex** [comment]
Results of my experience in PDF below
[denmark.pdf](https://github.com/DistanceDevelopment/distance-bugs/files/7090659/denmark.pdf)

I would say the repair has worked.  Laura will you post to the list, making sure Rasmus and Ainars see it.

**Comment by LHMarshall** [comment]
I have also copied the changes into the Win10 VM so I am going to close this issue as resolved with intermediate fix now advertised and permanent fix due with next release.
