### ISSUE TITLE
Adding ability to specify decimal separator in activity shiny

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/distance-bugs#206]
It'd be great to have the ability to specify the decimal separator in the activity shiny, before exporting the bootstrap activity values to file.  I think this means adding a drop-down so the user can specify "." (the default) or "," and then passing their choice along to the `write.table` call using the `dec=` option.

The reason to request this is that Distance for Windows expects the decimal separator to be the correct one for the locale the user is in, so it's expecting a `,` in some locales.

We need to have a user-specified option in the shiny rather than automatically sensing it because the shiny server doesn't know what locale the user is running shiny from.

**Comment by erex** [comment]
This issue should be relocated to repo where the Shiny code resides
