### ISSUE TITLE
problems to correctly identify distance and cluster size data in CDS analysis

### ISSUE THREAD

**Issue by andreitaaaa** [DistanceDevelopment/distance-bugs#208]
Hi people, 
I ‘ve been using the CDS engine for years without problems but a week ago I changed my pc disk, installed 7.4 version and I couldn’t make it work properly again. I have tried in another computer but the same problems arise. The import data wizard seems to work well and the data layers and column names are ok but the model warnings state that “one or more cluster sizes are 0” when there are no zeros in group size data, and the output show an incorrect mean cluster size. It seems that the engine is confounding distance and cluster size columns, averaging distances instead of group sizes, although the detection plot seems ok. I ´ve been checking regional options and txt formats but I can’t find the problem. 
Previous projects, built under the other versions, seem to run without problems but I can’t make the engine to read the data correctly in a new one. 
I ‘m not sure if this is a bug or I ‘m missing something, any suggestion is welcome. Thanks!
Mean perpendicular distance in this data set is 395 meters and mean group size is 10, but the output shows:
![image](https://user-images.githubusercontent.com/105927129/169538693-5bb83002-0afa-44f2-bd2c-9fe8e386bcdd.png)
![image](https://user-images.githubusercontent.com/105927129/169538844-0036caed-dcad-41d9-a5c1-fa2e8cffed85.png)

**Comment by erex** [comment]
Greetings @andreitaaaa.  Thanks for describing your problem.  To my knowledge, there's not been changes to the `file import` component of the software that might cause difficulties.

If you would be willing to share the file you input, I'd be happy to see what happens when I import it into Distance 7.4

If you don't want to include it in this public Github issue, you could email it to me at er26<at>st-andrews.ac.uk

**Comment by erex** [comment]
Temporary solution demonstrated here
https://www.loom.com/share/5f1ed8f4386e4ae380fac57795ee178e

**Comment by lenthomas** [comment]
I was also able to reproduce this on a newly installed version of Distance 7.4 (I wasn't on the version I'd had on my computer for a while, strangely).  I suspect it is something to do with changes made to the project setup wizard to accommodate camera trap surveys.  The problem appears to be that on project setup, the incorrect field is given role "Cluster size", as shown in this picture:
<img width="253" alt="Screenshot 2022-05-21 200331" src="https://user-images.githubusercontent.com/129519/169666200-1b7831e8-d945-4af7-a40d-e8355a09d040.png">
The circled entry should read "Cluster size".
A temporary workaround is to click on this and change it to "Cluster size" before performing any analyses.  We will work on a more permanent fix.

**Comment by LHMarshall** [comment]
This bug was also an issue for double observer projects created in Distance 7.4 release 1. We have now fixed this bug and published a second release of Distance 7.4 on our website. We advise users to update to Distance 7.4 release 2.
