### ISSUE TITLE
Get an error message when you run designs with new layer names that include a “.” or “_” (Bugzilla #63)

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/distance-bugs#89]
status NEW severity *minor* in component *05) Automated Survey Design* for *---*
Reported in version *6.0 Release 2* on platform *PC*
Assigned to: Laura Marshall

On 2010-09-16 02:26:35 +0100, Laura Marshall wrote:

> Get an error message when you run designs with new layer names that include a “.” or “_”. [18 June 01, David] [Len to fix]

**Comment by LHMarshall** [comment]
Think this is the same as #97

**Comment by LHMarshall** [comment]
See #132
