### ISSUE TITLE
Problems when a decimal point is included in the name of a design (Bugzilla #71)

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/distance-bugs#97]
status NEW severity *major* in component *05) Automated Survey Design* for *---*
Reported in version *6.0 Release 2* on platform *PC*
Assigned to: Laura Marshall

On 2010-09-16 03:03:14 +0100, Laura Marshall wrote:

> If you have a design name with a decimal point in it (e.g., 3.5km) then when you run the design to create a survey realization, the name of the survey will be 3.5km, and this means the name of the sample data layer will be 3.5km – but this is an illegal name in Distance.  Need to use a different name for the data layer, or not allow surveys with names that include characters that could not be layer names.  [LT 1 Sept 2010]

**Comment by LHMarshall** [comment]
See #132
